[package]
name = "rumina"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "^0.4"
num-rational = "^0.4"
num-traits = "^0.2"
rand = "^0.9"
chrono = "^0.4"
lazy_static = "^1.4"

[dev-dependencies]
criterion = "^0.7"
